### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by RedTopper** [RedInquisitive/Stronghold-2016#16]
Checklist for programming the robot.
# Todo:
- [x] Write code.
- [x] Program arm pneumatics when build is done.
- [x] Make sure camera works.
- [x] Get sensors running.
- [x] Make my code readable for future students.
### Kurt's Goals:
- [x] Pneumatics safety checks (Dumb Driver Checks).
- [x] Update/Document constants on a per robot basis
- [x] Bind pneumatics to Joysticks
- [ ] ~~Camera/Servo positioning code/mount~~
- [x] Initial Camera testing
- [ ] Photoelectric Sensor testing
- [ ] Ultrasonic Sensor testing

This is a test.

**Comment by RedTopper** [comment]
Whoo it worked! Just comment here to add to the task list. I'll move this to README.md if this is cool enough.

**Comment by J196W** [comment]
# Addedtodo:
- [x] Make code readable
- [ ] Solder resistors for Photoelectric Sensor
- [x] Create Raspberry Pi and config for streaming cameras
- [x] Get Mrs. Hosey to maybe purchase a Raspberry Pi 3 Model B

**Comment by wh1ter0se** [comment]
Jason my code will never be readable I code for compression not comprehension

**Comment by RedTopper** [comment]
:disappointed:

**Comment by J196W** [comment]
Comments for days.

**Comment by J196W** [comment]
Colton, I will still probably make a few comments so we know what the code
does without actually reading it.

**Comment by wh1ter0se** [comment]
Jason don't touch my code.

**Comment by wh1ter0se** [comment]
I can go through and clean it up if I have to but I think it can wait a day

**Comment by J196W** [comment]
I won't be touching your "code"

**Comment by kbowen99** [comment]
have we considered putting this on the readme?

**Comment by RedTopper** [comment]
Originally I just tested to see how checklists work with issues. (They show a progress bar on the issues tab, it looks like). Go for it.

**Comment by J196W** [comment]
So, are we moving this to the Readme?

**Comment by RedTopper** [comment]
> So, are we moving this to the Readme?

Kurt is.

**Comment by J196W** [comment]
Ok

**Comment by kbowen99** [comment]
ReadME Updated
